### ISSUE TITLE
What happened to the scripts directory

### ISSUE THREAD

**Issue by aaronscribner** [FabianGosebrink/ASPNET-Core-Angular2-StarterTemplate#7]
I just pulled latest and scripts/app is gone. Also would be good to add the wwwroot to the .gitignore.

**Comment by FabianGosebrink** [comment]
Hey @aaronscribner,
Did you run the gulp-task? wwwroot can not be in gitignore because the app lives in there. I will move that out eventually, its on my list. But for now it has to be in there.

BR

Fabian

**Comment by aaronscribner** [comment]
@FabianGosebrink 
There used to be a scripts directory in this location -- https://github.com/FabianGosebrink/ASPNET-Core-Angular2-StarterTemplate/tree/master/src/ASPNETCoreAngular2Demo

Yeah, well I meant the /app in the wwwroot, not the wwwroot itself (which is obviously not what I said).

**Comment by FabianGosebrink** [comment]
Hey @aaronscribner,
Did you run the gulp-task? It should create the scripts folder for you.

BR

Fabian

**Comment by aaronscribner** [comment]
I guess I confused myself between this and some other project templates I have seen. Where I would like to take this is to have all the scripts/ contain the Typescript files only and those are gulp'd to the wwwroot for ASPNET Core support. For whatever reason, I thought that is the way this one works.

**Comment by FabianGosebrink** [comment]
Well it works on many ways, but gulping the files to wwwroot is the common way to do it. Give me a little time, currently working on this approach. Then you'll have a folder on root which is gulped to wwwroot and wwwroot only contains what is served.


BR





On Wed, Sep 28, 2016 at 4:48 PM +0200, "aaronscribner" <notifications@github.com> wrote:





I guess I confused myself between this and some other project templates I have seen. Where I would like to take this is to have all the scripts/ contain the Typescript files only and those are gulp'd to the wwwroot for ASPNET Core support. For whatever reason, I thought that is the way this one works.

**Comment by aaronscribner** [comment]
That will be nice. I really like what you have done here. Most of the templates or Yeoman are really out of date (for the MEAN stack). We are hopefully moving to Angular2 for the next client project here very shortly and stuff like this helps us focus on the business task at hand.

I was going to start on moving the stuff like you mentioned, let me know if you need any help.

BTW, the "get-started" gulp command, what do you think about renaming it to "default". That should allow you to just run "gulp" from the cli instead of "gulp get-started". I use PowerShell most of the time to build the client. I did try that other fork of this in which the guy added gulp to the compilation, but I do now agree with leaving that out of the default VS build process. I do not want to always wait for the client to gulp if I am building a back-end service.

**Comment by FabianGosebrink** [comment]
Hey @aaronscribner ,

I think to get you less confused (or not confused at all in the end :) we need to take a step back and see how this all works or which are a few of the thousand ways this could work.

Since the new ASP.NET we know that everything inside the wwwroot folder gets served to the client. So the question was: Do I develop inside the wwwroot folder and before distributing I strip the folder containing only the files that I need (like bundles and stuff)? Or do I develop outside and just copy the files into the wwwroot folder when I want to publish? These are two different approaches. The second one is the more common, as you mentioned.

(To get more conusing here: Sometimes I do seperate the Client and the Server that I do a seperate ".dist"-Folder and do not use the wwwroot at all. You have to use the wwwroot folder only if you publish the Api and the wwwroot files through Visual Studio and on the same server. But in the case the Client application has to live somewhere else you have to have a dist-folder (or use wwwroot and copy the files out in the end). But that is not relevant right here right now.

The reason why I decided to put the development files in the wwwroot in the beginning was the auto reload. Because when you start the repo with `npm start` a lite server starts and opens up the browser. Now if you edit files the lite-server only know that the files have been modified when they were modified from the folder he serves the files from. To offer the feature I put everything inside the wwwroot first.

But this approach was not that common anymore and got confusing. So right now I moved the whole "wwwroot/app" folder to the root and renamed it "angular2app" to be clear that your angular2app lives there. The gulp task `get:started` is now copying all the needed files (only js, html and css) to the wwwroot folder so it contains only what is needed. But at this point you have no auto reload with lite-server anymore. Because you are developing *.ts in folder "angular2app" and serving from "wwwroot". 

To resolve this I created a watcher which is copying the files with gulp to wwwroot and the lite-server is triggered due to the copying process.

I hope the topic gets clearer right now.

> the "get-started" gulp command, what do you think about renaming it to "default".

I do not like this approach because of two reasons:

1) As a developer the first thing you do when you start with a project (and I have seen this so many times) is typing `gulp` into the console. And then "something" happens. And you have no clue what was going on right now but something happened. I do like the approach more to have tasks named precisely of what they are doing. I prefer to use something like "task-listing" to give the developer, who immediatelly types "gulp" in the console an overview of what he can do. Afterwards he can decide what he is going to do. You can see that in my other repos. Of course this is very personal and subjective, its just my way of doing it. Many customers I do consult do have a default task which is abslutely fine for me :)

2) I like to hang out all commands with npm. Web development is using tons of tools and its so hard to have this tool doing this and that tool doing that...I like to have npm and you can trigger every important action through `npm ...` or `npm run ...`.

But again: This is my way of doing it because I made the best experiences with that. Any other way is totally fine :)

And last but not least: Thank you for commenting here and for the kind words on this repo :)

BR

Fabian

**Comment by aaronscribner** [comment]
Nice reply and you are welcome.

My last project was a major Angular project and I was simultaneously fortunate and unfortunate to not set it up from scratch, that was done by another consultant in the group. 

I come from a heavy ASPNET MVC background and that is the only tech stack I used for web until learning Angular.

I can see the points of what you posted. On our last project, we had all the Typescript (Angular 1) in the scripts directory and it was gulp'd to the dist directory. That model worked very well, but we were not always following the best Angular practices either. I am still learning Angular, so I am open to try different things to find out what is the most efficient way to complete a project.

I look forward to following your changes on this.

**Comment by FabianGosebrink** [comment]
You are welcome :) Thanks for following and pointing out issues. I really appreciate that.
